/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package principal;

import java.time.LocalDate;

import java.time.format.DateTimeFormatter;

import principal.clases.IJugador;
import principal.clases.IUsuario;
import principal.clases.Usuario;

public class Main {
	
	public static final String FORMATOFECHA = "dd-MM-yyyy";

	@SuppressWarnings("unused")
	public static void main(String[] args) {

		IUsuario u1 = new Usuario();
		IUsuario u2 = new Usuario("Antonio",getFecha("05-09-1984"));
		IUsuario u3 = new Usuario("Juana",getFecha("05-09-1985"));
		
		System.out.println(u1);
		System.out.println(u2);
		System.out.println(u3);
		

		IJugador j1 = (IJugador)u1;
		IJugador j2 = (IJugador)u2;
		IJugador j3 = (IJugador)u3;

	}

	public static LocalDate getFecha(String fecha) {
		return LocalDate.parse(fecha,DateTimeFormatter.ofPattern(FORMATOFECHA));
	}

}
